# Generated by Django 4.1 on 2023-11-16 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=10, null=True)),
                ('jumlah', models.IntegerField()),
                ('satuan', models.CharField(blank=True, max_length=10, null=True)),
                ('expired', models.DateField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('Masuk', 'MASUK'), ('Keluar', 'KELUAR')], default='Masuk', max_length=7)),
                ('jumlah', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
