# Generated by Django 3.2.6 on 2023-09-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='admin_id',
        ),
    ]
