# Generated by Django 3.2.6 on 2023-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stock_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='jenis',
            field=models.CharField(choices=[('Masuk', 'MASUK'), ('Keluar', 'KELUAR')], default='Masuk', max_length=7),
        ),
    ]
