# Generated by Django 4.1 on 2023-12-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_history_updated_by_alter_stock_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='jenis',
            field=models.CharField(choices=[('Masuk', 'MASUK'), ('Keluar', 'KELUAR'), ('Edit', 'EDIT')], default='Masuk', max_length=7),
        ),
    ]
