# Generated by Django 4.1 on 2023-12-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_history_jenis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='added_by',
        ),
        migrations.AddField(
            model_name='stock',
            name='merchant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
