# Generated by Django 4.2.5 on 2023-10-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0004_alter_stock_stock_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="satuan",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
