# Generated by Django 4.1 on 2023-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_stock_added_by_stock_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='jenis',
            field=models.CharField(choices=[('In', 'MASUK'), ('Out', 'KELUAR'), ('Edit', 'EDIT')], default='In', max_length=7),
        ),
    ]
