# Generated by Django 4.1 on 2023-10-23 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_satuan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='jenis',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('Masuk', 'MASUK'), ('Keluar', 'KELUAR')], default='Masuk', max_length=7)),
                ('jumlah', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
