# Generated by Django 4.1 on 2023-12-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_history_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='nama',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
