# Generated by Django 4.1 on 2023-10-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_stock_jenis_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
