# Generated by Django 4.1 on 2023-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_history_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='satuan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
