# Generated by Django 4.2.5 on 2023-10-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0008_history_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="nama",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
