# Generated by Django 4.1 on 2023-12-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0009_alter_history_jumlah_alter_stock_jumlah"),
    ]

    operations = [
        migrations.RemoveField(model_name="history", name="nama",),
        migrations.RemoveField(model_name="history", name="satuan",),
        migrations.RemoveField(model_name="history", name="updated_by",),
        migrations.RemoveField(model_name="stock", name="merchant",),
        migrations.AlterField(
            model_name="history",
            name="jenis",
            field=models.CharField(
                choices=[("Masuk", "MASUK"), ("Keluar", "KELUAR")],
                default="Masuk",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="history", name="jumlah", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="stock", name="jumlah", field=models.IntegerField(),
        ),
    ]
