# Generated by Django 4.1 on 2023-12-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0010_remove_history_nama_remove_history_satuan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="merchant",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
