# Generated by Django 4.1 on 2023-12-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_history_jumlah_alter_stock_jumlah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='jenis',
            field=models.CharField(choices=[('Masuk', 'MASUK'), ('Keluar', 'KELUAR'), ('Edit', 'EDIT')], default='Masuk', max_length=7),
        ),
    ]
