# Generated by Django 4.1 on 2023-12-21 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0014_alter_history_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='jenis',
            field=models.CharField(choices=[('In', 'MASUK'), ('Out', 'KELUAR'), ('Edit', 'EDIT'), ('Create', 'BUAT')], default='In', max_length=7),
        ),
    ]
